name: orbirag
description: "AI-Powered Research Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  google_sign_in: ^7.2.0
  
  # Storage & State
  shared_preferences: ^2.5.5
  
  # Speech & Audio
  speech_to_text: ^7.4.0
  record: ^5.1.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  loading_animation_widget: ^1.2.1

  
  # File Handling
  file_picker: ^8.0.0
  image_picker: ^1.1.2
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Networking
  http: ^1.2.0
  
  # UI Enhancements
  flutter_animate: ^4.5.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  

 flutter:
  assets:
    - assets/images/
    - .env