// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwJqVtvpvzJTvu_g0rzg2wwsyhfLSEg7g',
    appId: '1:407358214556:web:2cd1ef3223b289011cf859',
    messagingSenderId: '407358214556',
    projectId: 'orbirag-2816b',
    authDomain: 'orbirag-2816b.firebaseapp.com',
    storageBucket: 'orbirag-2816b.firebasestorage.app',
    measurementId: 'G-QFH33Q01WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FzQZIsFq0crDL4cvBJuaKornyEXofn4',
    appId: '1:407358214556:android:bc4757ed198780f11cf859',
    messagingSenderId: '407358214556',
    projectId: 'orbirag-2816b',
    storageBucket: 'orbirag-2816b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiDcWmGxspHPre0jfJlMW8xjQHu9Sh7iU',
    appId: '1:407358214556:ios:a94da9d554bb81bf1cf859',
    messagingSenderId: '407358214556',
    projectId: 'orbirag-2816b',
    storageBucket: 'orbirag-2816b.firebasestorage.app',
    iosBundleId: 'com.scholarPulse.shreya.scholarPulse',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiDcWmGxspHPre0jfJlMW8xjQHu9Sh7iU',
    appId: '1:407358214556:ios:a94da9d554bb81bf1cf859',
    messagingSenderId: '407358214556',
    projectId: 'orbirag-2816b',
    storageBucket: 'orbirag-2816b.firebasestorage.app',
    iosBundleId: 'com.scholarPulse.shreya.scholarPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwJqVtvpvzJTvu_g0rzg2wwsyhfLSEg7g',
    appId: '1:407358214556:web:679b0ae1447a975a1cf859',
    messagingSenderId: '407358214556',
    projectId: 'orbirag-2816b',
    authDomain: 'orbirag-2816b.firebaseapp.com',
    storageBucket: 'orbirag-2816b.firebasestorage.app',
    measurementId: 'G-YEPD8BCJQJ',
  );
}
